#!/bin/sh
# dockname generator: watches Docker and gives every container with a published
# port a <name>.localhost URL, by writing a Traefik dynamic config file.
#
#   generator.sh            watch Docker and keep /routes up to date (default)
#   generator.sh once       write the routes once and exit
#   generator.sh plan       read `docker ps` lines on stdin, print routes
#   generator.sh yaml       read routes on stdin, print the Traefik config
#   generator.sh html       read routes on stdin, print the dashboard page
#   generator.sh json       read routes on stdin, print them as JSON
#
# A route line is: id|host1,host2|host_port|container_name
set -eu

DOMAIN=${DOCKNAME_DOMAIN:-localhost}
OUT=${DOCKNAME_OUT:-/routes}
UPSTREAM=${DOCKNAME_UPSTREAM:-host.docker.internal}
PREFERRED=${DOCKNAME_PREFERRED_PORTS:-80 8080 3000 8000 5173 4200 5000 8888 9000}
INDEX_URL=${DOCKNAME_INDEX_URL:-http://dockname-index:80}
RULES=${DOCKNAME_RULES:-/dockname/rules.sed}

FORMAT='{{.Names}}	{{.Ports}}	{{.Label "dockname.enable"}}	{{.Label "dockname.host"}}	{{.Label "dockname.port"}}	{{.Label "com.docker.compose.project"}}	{{.Label "com.docker.compose.service"}}'

# Optional naming rules: a `sed -E` script run on each container name. The first
# line it prints becomes the host (the domain is appended when missing), e.g.
#   s/^myapp-([a-z0-9]+)$/\1.myapp/p    myapp-feat42 -> feat42.myapp.localhost
# The rule host goes in an extra 8th column; a dockname.host label still wins.
rules() {
  if [ ! -f "$RULES" ]; then cat; return; fi
  while IFS= read -r line; do
    name=$(printf '%s\n' "$line" | cut -f1)
    host=$(printf '%s\n' "$name" | sed -nE -f "$RULES" | head -n 1)
    printf '%s\t%s\n' "$line" "$host"
  done
}

# stdin: one tab-separated line per container (FORMAT above) -> stdout: routes
plan() {
  awk -F '\t' -v domain="$DOMAIN" -v preferred="$PREFERRED" '
    function clean(s) {
      s = tolower(s); gsub(/[^a-z0-9-]+/, "-", s); gsub(/^-+|-+$/, "", s); return s
    }
    function fqdn(h) {
      h = tolower(h); gsub(/^[ \t]+|[ \t]+$/, "", h)
      if (h == "" || h ~ /[^a-z0-9.-]/) return ""
      if (h == domain || substr(h, length(h) - length(domain)) == "." domain) return h
      return h "." domain
    }
    function add(h) {
      if (h == "" || (h in taken)) return
      taken[h] = 1; hosts = hosts (hosts == "" ? "" : ",") h
    }
    BEGIN { np = split(preferred, pref, " ") }
    {
      name = $1; ports = $2; enable = tolower($3); label = $4; want = $5; proj = $6; svc = $7
      if (label == "") label = $8
      if (name == "" || enable == "false" || enable == "no" || enable == "0") next

      # host port for each published container port (IPv4/IPv6 wildcard, TCP only)
      delete map; first = ""
      n = split(ports, entries, /, */)
      for (i = 1; i <= n; i++) {
        e = entries[i]
        if (e !~ /^(0\.0\.0\.0|\[::\]|::):[0-9]+->[0-9]+\/tcp$/) continue
        sub(/^.*:/, "", e); split(e, hp, "->"); sub(/\/tcp$/, "", hp[2])
        if (!(hp[2] in map)) map[hp[2]] = hp[1]
        if (first == "") first = hp[1]
      }
      port = ""
      if (want != "") port = (want in map) ? map[want] : ""
      else {
        for (i = 1; i <= np && port == ""; i++) if (pref[i] in map) port = map[pref[i]]
        if (port == "") port = first
      }
      if (port == "") next

      hosts = ""
      if (label != "") {
        m = split(label, wanted, ",")
        for (i = 1; i <= m; i++) add(fqdn(wanted[i]))
      } else {
        id = clean(name)
        if (proj != "" && svc != "") {
          p = clean(proj); s = clean(svc); alias = s "." p
          # compose default names: <project>-<service>-<n> -> <service>.<project>
          if (id ~ ("^" p "-" s "-[0-9]+$")) {
            num = id; sub(/^.*-/, "", num)
            add((num == "1" ? alias : s "-" num "." p) "." domain)
          } else {
            add(id "." domain); add(alias "." domain)
          }
        } else add(id "." domain)
      }
      if (hosts == "") next
      print clean(name) "|" hosts "|" port "|" name
    }'
}

# stdin: routes -> stdout: Traefik dynamic config (always valid, even with no routes)
yaml() {
  awk -F '|' -v upstream="$UPSTREAM" -v domain="$DOMAIN" -v index_url="$INDEX_URL" '
    { id[NR] = $1; hosts[NR] = $2; port[NR] = $3 }
    END {
      print "# Generated by dockname. Do not edit: it is rewritten on every container start/stop."
      print "http:"
      print "  routers:"
      print "    dockname-index:"
      print "      rule: \"Host(`dockname." domain "`)\""
      print "      service: dockname-index"
      for (i = 1; i <= NR; i++) {
        n = split(hosts[i], h, ","); rule = ""
        for (j = 1; j <= n; j++) rule = rule (j > 1 ? " || " : "") "Host(`" h[j] "`)"
        print "    c-" id[i] ":"
        print "      rule: \"" rule "\""
        print "      service: c-" id[i]
      }
      print "  services:"
      print "    dockname-index:"
      print "      loadBalancer:"
      print "        servers:"
      print "          - url: \"" index_url "\""
      for (i = 1; i <= NR; i++) {
        print "    c-" id[i] ":"
        print "      loadBalancer:"
        print "        passHostHeader: true"
        print "        servers:"
        print "          - url: \"http://" upstream ":" port[i] "\""
      }
    }'
}

# stdin: routes -> stdout: dashboard page listing every URL
html() {
  awk -F '|' -v domain="$DOMAIN" -v http_port="${DOCKNAME_HTTP_PORT:-80}" '
    function esc(s) { gsub(/&/, "\\&amp;", s); gsub(/</, "\\&lt;", s); gsub(/>/, "\\&gt;", s); gsub(/"/, "\\&quot;", s); return s }
    { rows = rows "<tr><td>" esc($4) "</td><td>"
      n = split($2, h, ",")
      for (j = 1; j <= n; j++) {
        url = "http://" h[j] (http_port == "80" ? "" : ":" http_port) "/"
        rows = rows "<a href=\"" esc(url) "\">" esc(h[j]) "</a>" (j < n ? "<br>" : "")
      }
      rows = rows "</td><td>" esc($3) "</td></tr>\n"
    }
    END {
      print "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
      print "<meta http-equiv=\"refresh\" content=\"5\"><title>dockname</title><style>"
      print ":root{color-scheme:light dark;--fg:#1f2328;--bg:#fff;--mute:#59636e;--line:#d1d9e0;--link:#0969da}"
      print "@media(prefers-color-scheme:dark){:root{--fg:#f0f6fc;--bg:#0d1117;--mute:#9198a1;--line:#3d444d;--link:#4493f8}}"
      print "body{font:15px/1.5 system-ui,sans-serif;color:var(--fg);background:var(--bg);margin:0;padding:24px 16px}"
      print "main{max-width:860px;margin:auto}h1{margin:0 0 4px}p{color:var(--mute);margin:0 0 20px}"
      print "table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:8px 10px;border-bottom:1px solid var(--line);vertical-align:top}"
      print "th{color:var(--mute);font-weight:600}a{color:var(--link);text-decoration:none}a:hover{text-decoration:underline}"
      print "</style></head><body><main><h1>dockname</h1>"
      print "<p>" NR " container" (NR == 1 ? "" : "s") " with a URL on <b>*." esc(domain) "</b>. This page refreshes every 5 seconds.</p>"
      if (NR == 0) print "<p>No running container publishes a TCP port yet. Start one with <code>docker run -p 8081:80 --name hello nginx</code> and open <b>hello." esc(domain) "</b>.</p>"
      else print "<table><thead><tr><th>Container</th><th>URL</th><th>Host port</th></tr></thead><tbody>\n" rows "</tbody></table>"
      print "</main></body></html>"
    }'
}

# stdin: routes -> stdout: JSON array, for scripts and editor extensions
json() {
  awk -F '|' -v http_port="${DOCKNAME_HTTP_PORT:-80}" '
    function q(s) { gsub(/\\/, "\\\\", s); gsub(/"/, "\\\"", s); return "\"" s "\"" }
    BEGIN { printf "[" }
    { n = split($2, h, ","); hs = ""
      for (j = 1; j <= n; j++) hs = hs (j > 1 ? "," : "") q(h[j])
      printf "%s\n  {\"container\": %s, \"hosts\": [%s], \"url\": %s, \"hostPort\": %d}", (NR > 1 ? "," : ""), q($4), hs, q("http://" h[1] (http_port == "80" ? "" : ":" http_port) "/"), $3 }
    END { print (NR ? "\n" : "") "]" }'
}

# write $2 to $1 only when the content changed (each rewrite makes Traefik reload)
put() {
  if ! cmp -s "$2" "$1"; then mv "$2" "$1"; else rm -f "$2"; fi
}

once() {
  mkdir -p "$OUT/www"
  routes=$(mktemp)
  docker ps --format "$FORMAT" | rules | plan | sort -t "|" -k 4 > "$routes"
  yaml < "$routes" > "$OUT/.routes.yml.tmp" && put "$OUT/routes.yml" "$OUT/.routes.yml.tmp"
  html < "$routes" > "$OUT/www/.index.html.tmp" && put "$OUT/www/index.html" "$OUT/www/.index.html.tmp"
  json < "$routes" > "$OUT/www/.routes.json.tmp" && put "$OUT/www/routes.json" "$OUT/www/.routes.json.tmp"
  echo "dockname: $(wc -l < "$routes" | tr -d ' ') route(s)"
  rm -f "$routes"
}

watch() {
  once
  while :; do
    docker events --filter type=container --filter event=start --filter event=die \
      --filter event=rename --format '{{.Status}}' | while read -r _; do
      # coalesce bursts (compose up starts many containers at once)
      sleep 1; once
    done
    echo "dockname: lost the Docker event stream, retrying" >&2
    sleep 2; once || true
  done
}

case "${1:-watch}" in
  watch) watch ;;
  once) once ;;
  plan) rules | plan ;;
  yaml) yaml ;;
  html) html ;;
  json) json ;;
  *) echo "usage: $0 [watch|once|plan|yaml|html|json]" >&2; exit 2 ;;
esac
